# Generated by Django 6.0.5 on 2026-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodecache',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='город'),
        ),
    ]
