# Generated by Django 5.1.3 on 2025-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_response_is_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('request', 'carrier')},
        ),
        migrations.AlterField(
            model_name='response',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='response',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='response',
            name='message',
        ),
    ]
