# Generated by Django 6.0.5 on 2026-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_optout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=16),
        ),
    ]
