# Generated by Django 6.0.5 on 2026-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон (E.164)')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Telegram chat id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
