# Generated by Django 6.0.5 on 2026-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_eta_at_delivery_eta_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dest_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='город назначения'),
        ),
    ]
