# Generated by Django 6.0.5 on 2026-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='удалена'),
        ),
        migrations.AddField(
            model_name='shop',
            name='completed_expanded',
            field=models.BooleanField(default=False, verbose_name='секция «завершённые» развёрнута'),
        ),
    ]
