# Generated by Django 6.0.5 on 2026-06-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_delivery_deleted_at_shop_completed_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='kanban_view',
            field=models.BooleanField(default=False, verbose_name='вид «канбан-доска»'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('created', 'Spremno'), ('on_the_way', 'U dostavi'), ('delivered', 'Završeno')], default='new', max_length=12),
        ),
    ]
