# Generated by Django 6.0.5 on 2026-06-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_shop_kanban_view_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('created', 'Ready'), ('on_the_way', 'In delivery'), ('delivered', 'Done')], default='new', max_length=12),
        ),
    ]
